In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('icu.csv')
df.shape

(1023, 11)

In [4]:
df

patient_id                  disease  age  gender   adm_type  bpm  \
0           1000   Traumatic Brain Injury   58       1     urgent  120   
1           1001                   Stroke   40       1     urgent   45   
2           1002  Ruptured Brain Aneurysm   69       0   elective  123   
3           1003  Ruptured Brain Aneurysm   22       0  emergency   60   
4           1004                   Sepsis   56       1  emergency  116   
...          ...                      ...  ...     ...        ...  ...   
1018        2096                   Stroke   78       1  emergency  113   
1019        2097                    Shock   57       0     urgent   44   
1020        2098   Traumatic Brain Injury   39       1  emergency  115   
1021        2099   Traumatic Brain Injury   72       1     urgent  128   
1022        2100   Traumatic Brain Injury   33       1     urgent  125   

      body_temp(°F)  resp_rate  oxy_sat  days_in_icu  death  
0              98.2          7       88            8      1  
1              98.0         14       88            1      1  
2              98.6         11       95            9      1  
3              97.8          7       89            7      1  
4             100.5         13       93            4      1  
...             ...        ...      ...          ...    ...  
1018          100.6         11      100            2      1  
1019          100.7         15       98           14      0  
1020          100.2         13       85           12      1  
1021          100.4          9       97            6      0  
1022           99.3          7       87           10      0  

[1023 rows x 11 columns]

In [11]:
x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],remainder='passthrough')
x=np.array(columnTransformer.fit_transform(x))

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [7])],remainder='passthrough')
x=np.array(columnTransformer.fit_transform(x))

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .25,random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# DT

In [163]:
from sklearn.tree import DecisionTreeClassifier

classifier1 = DecisionTreeClassifier(random_state = 0, criterion='gini')
classifier1.fit(x_train, y_train)

y_pred_1 = classifier1.predict(x_test)

In [164]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_1)
print(cm)
print(accuracy_score(y_test, y_pred_1))

[[60 78]
 [55 63]]
0.48046875


In [165]:
classifier1 = DecisionTreeClassifier(random_state = 0, criterion='entropy')
classifier1.fit(x_train, y_train)

y_pred_1 = classifier1.predict(x_test)

In [166]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_1)
print(cm)
print(accuracy_score(y_test, y_pred_1))

[[45 93]
 [51 67]]
0.4375


# LR

In [167]:
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression(random_state = 0)
classifier2.fit(x_train, y_train)

y_pred_2 = classifier2.predict(x_test)

In [168]:
cm = confusion_matrix(y_test, y_pred_2)
print(cm)
print(accuracy_score(y_test, y_pred_2))

[[ 29 109]
 [ 22  96]]
0.48828125


# KNN

In [169]:
from sklearn.neighbors import KNeighborsClassifier
classifier3 = KNeighborsClassifier(n_neighbors=15, metric='minkowski', p=2)
classifier3.fit(x_train, y_train)

y_pred_3 = classifier3.predict(x_test)

In [170]:
cm = confusion_matrix(y_test, y_pred_3)
print(cm)
print(accuracy_score(y_test, y_pred_3))

[[57 81]
 [37 81]]
0.5390625


# SVM

In [171]:
from sklearn.svm import SVC
classifier4 = SVC(kernel='rbf')
classifier4.fit(x_train,y_train)

y_pred_4 = classifier4.predict(x_test)

In [172]:
cm = confusion_matrix(y_test, y_pred_4)
print(cm)
print(accuracy_score(y_test, y_pred_4))

[[58 80]
 [28 90]]
0.578125


# NB

In [173]:
from sklearn.naive_bayes import GaussianNB
classifier5 = GaussianNB()
classifier5.fit(x_train, y_train)

y_pred_5 = classifier5.predict(x_test)

In [174]:
cm = confusion_matrix(y_test, y_pred_5)
print(cm)
print(accuracy_score(y_test, y_pred_5))

[[53 85]
 [45 73]]
0.4921875


# RF

In [177]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators=10)
classifier6.fit(x_train,y_train)

y_pred_6 = classifier6.predict(x_test)

In [178]:
cm = confusion_matrix(y_test, y_pred_6)
print(cm)
print(accuracy_score(y_test, y_pred_6))

[[66 72]
 [70 48]]
0.4453125
